package com.dcits.selenium.sonic.sonicAutoTest;// Generated by Selenium IDE

import com.dcits.entity.EnumSonic;
import com.dcits.util.DriverUtil;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

import java.util.HashMap;
import java.util.Map;

public class SonicUiWorkManageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String jobState = EnumSonic.getName(2);
  @Test
  public void sonicWorkManage() throws InterruptedException {
  /*  String applyName = "lytest";
    String jobName = "L-TXT文件分段测试";*/
    //应用名称内容点击填充筛选
    /*String applyName = map.get("applyName");
    String jobName = map.get("jobName");
    String url = map.get("url");
    String username = map.get("username");
    String password = map.get("password");*/
    String applyName = "ly01";
    String jobName = "L-TXT文件分段测试";
    String url = "http://10.7.19.116:31561";
    String username = "liuyiag";
    String password = "liuyi0526";
    applyName = "//span[contains(.,"+"'"+applyName+"'"+")]";
    //job名称内容点击填充筛选
    String  combinName =  "//span[contains(.,"+"'"+jobName+"'"+")]";
    //调用chrome
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver = DriverUtil.getFiedFoxDriver("E:\\firefox_driver\\geckodriver.exe");
    driver.get(url);
    driver.manage().window().maximize();
    driver.findElement(By.name("username")).sendKeys(username);
    driver.findElement(By.name("password")).sendKeys(password);
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector("span")).click();
    Thread.sleep(1500);
    driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/ul/li[3]")).click();//作业管理
    Thread.sleep(1500);
    //作业管理job列表筛选查看启动job操作
    showAndRunJob(driver,applyName,jobName,combinName);
    //作业管理job运行消息
    jobRunMessage(driver,applyName,jobName,combinName);
    //作业管理JOB运行历史
    jobRunHistory(driver,applyName,jobName,combinName);
    //关闭标签，退出自动化
    Thread.sleep(1500);
    driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[1]/div[2]/div")).click();
    Thread.sleep(1500);
//    driver.findElement(By.xpath("//body/ul/li[2]")).click();
    Thread.sleep(1500);
    driver.close();
  }

    /*JOB列表，查看运行job*/
  public void showAndRunJob(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
    //左侧作业管理页签点击
    this.driver.findElement(By.xpath("//li[3]/ul/li")).click();
    Thread.sleep(1500);
    //多个应用会模糊搜索出现默认选择第一个
   //筛选应用名称
    this.driver.findElement(By.xpath("//input[@type='text']")).click();
    Thread.sleep(1500);
    this.driver.findElement(By.xpath(applyName)).click();
    Thread.sleep(1500);
    //筛选Job名称
    this.driver.findElement(By.xpath("//div[2]/div/div/div/span/span/i")).click();
    Thread.sleep(1500);
    this.driver.findElement(
            By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/form/div[2]/div/div/div/input")).sendKeys(jobName);
    Thread.sleep(1500);
    this.driver.findElement(By.xpath(combinName)).click();
    Thread.sleep(1500);
    //搜索按钮点击
    this.driver.findElement(By.cssSelector(".el-icon-search")).click();
    Thread.sleep(1500);
    //结果信息操作区域点击
    this.driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[3]/table/tbody/tr/td[9]/div/div")).click();
    Thread.sleep(1500);
    //查看功能
    this.driver.findElement(By.xpath("//body/ul/li")).click();
    Thread.sleep(1500);
    //启动前查看暂时搁置
     /* driver.findElement(By.xpath("//div[2]/div/div/button/i")).click();
      driver.findElement(By.xpath("/html/body/div[7]/div/div[1]/button")).click();*/
    //启动按钮
    this.driver.findElement(By.xpath("//*[@id=\"content\"]/div[2]/button[1]")).click();
    Thread.sleep(1500);
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-button--warning:nth-child(1) > span"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
      Thread.sleep(1000);
    }

    {
      WebElement element = this.driver.findElement(By.tagName("body"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element, 0, 0).perform();
      Thread.sleep(500);
    }
    //启动确定按钮
    this.driver.findElement(By.cssSelector(".el-dialog__footer:nth-child(3) .el-button--primary > span")).click();
    Thread.sleep(1500);
    /*画布右键点击暂时搁置*/
   /* driver.findElement(By.xpath("//ul[@id='jobStepCanvas-contextmenu']/li")).click();
    driver.findElement(By.id("tab-second")).click();//分段运行信息弹框
    driver.findElement(By.cssSelector(".close-btn")).click();
      Thread.sleep(1000);*/
    //作业管理jJob列表end
  }
  /*作业管理JOB运行信息*/
  public void jobRunMessage(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
    this.driver.findElement(By.xpath("//span[contains(.,'JOB运行信息')]")).click();
    Thread.sleep(1500);
    //应用名称+job名称搜索，进行接下来操作
    runSuccMessageFilter(driver,applyName,jobName,combinName);
    Thread.sleep(1500);
  }
  /*作业管理job运行消息之查看step信息操作*/
  private void showOpertStepRunMessage(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
    //点击step文件分段测试，>符号点击操作
    Thread.sleep(1500);
    driver.findElement(By.cssSelector(".el-table__expand-icon > .el-icon")).click();
    Thread.sleep(1500);
   //点击查看step运行消息
    this.driver.findElement(By.xpath("//td[10]/div/div/button/span")).click();
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-dropdown > .el-button--text > span"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
      Thread.sleep(1000);
    }
    {
      WebElement element = this.driver.findElement(By.tagName("body"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element, 0, 0).perform();
      Thread.sleep(1500);
    }
   // Thread.sleep(1000);
    //点击查看step操作区域
    this.driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(1) > .el-button--text")).click();
    Thread.sleep(1500);
    //点击查看错误运行信息
    this.driver.findElement(By.xpath("//div[6]/div/div/button/i")).click();
    Thread.sleep(1500);
    //点击查看step操作区域
    this.driver.findElement(By.xpath("//td[10]/div/div/button/span")).click();
    Thread.sleep(1500);
    //查看分段运行信息
    this.driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(2) span")).click();
    //作业管理job运行消息end
    Thread.sleep(1500);
  }

  /*job运行信息页面，点击操作查看job运行信息*/
  public void showOpertJobRunMessage(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
    this.driver.findElement(By.xpath("/html/body/div/div/div[2]/div[2]/div/div/div/div[2]/div[4]/div[2]/table/tbody/tr/td[8]/div/div")).click();
    Thread.sleep(1500);
    this.driver.findElement(By.xpath("//body/ul/li[2]/button/span")).click();
    Thread.sleep(1500);
    {
      WebElement element = this.driver.findElement(By.tagName("body"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element, 0, 0).perform();
      Thread.sleep(1500);
    }
    this.driver.findElement(By.id("jobStepCanvas")).click();
    //右键操作暂时搁置
    /*driver.findElement(By.cssSelector("#jobStepCanvas-contextmenu > li")).click();//查看详情操作
    driver.findElement(By.id("tab-second")).click();
    driver.findElement(By.cssSelector(".close-btn")).click();*/
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-icon-arrow-down:nth-child(1)"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
      Thread.sleep(1500);
    }
    {
      WebElement element = this.driver.findElement(By.tagName("body"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element, 0, 0).perform();
      Thread.sleep(1000);
    }
    this.driver.findElement(By.cssSelector(".is-opened .el-menu-item:nth-child(2) > span")).click();
    Thread.sleep(1000);
    this.driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[4]/div[2]/table/tbody/tr/td[8]/div/div")).click();//查看运行信息，点击操作
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-table__fixed-body-wrapper .el-dropdown > .el-button > span"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
      Thread.sleep(1000);
    }
    {
      WebElement element = this.driver.findElement(By.tagName("body"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element, 0, 0).perform();
      Thread.sleep(1000);
    }
    this.driver.findElement(By.xpath("//body/ul/li[1]/button/span")).click();
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-table__body-wrapper"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).clickAndHold().perform();
      Thread.sleep(1000);
    }
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-table__body-wrapper"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).perform();
      Thread.sleep(1000);
    }
    {
      WebElement element = this.driver.findElement(By.cssSelector(".el-table__body-wrapper"));
      Actions builder = new Actions(this.driver);
      builder.moveToElement(element).release().perform();
      Thread.sleep(1000);
    }
  }
  /*job运行信息条件筛选*/
  public void  runSuccMessageFilter(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
    //筛选应用名称
    this.driver.findElement(By.xpath("//input[@type='text']")).click();
    Thread.sleep(1000);
    this.driver.findElement(By.xpath(applyName)).click();
    Thread.sleep(1000);
    //筛选job名称
    this.driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/form/div[2]/div/div/div[1]")).click();
    Thread.sleep(1000);
    this.driver.findElement(
            By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/form/div[2]/div/div/div[1]/input")).sendKeys(jobName);
    Thread.sleep(1000);
    this.driver.findElement(By.xpath(combinName)).click();
    Thread.sleep(1000);
    //任务状态筛选
/*      this.driver.findElement(By.xpath("(//input[@type='text'])[3]")).click();
      Thread.sleep(1000);
      this.driver.findElement(By.xpath(applyName)).click();
      Thread.sleep(1000);*/
      //搜索按钮点击
    this.driver.findElement(By.xpath("//div[5]/div/button/span")).click();
    Thread.sleep(1000);
    this.driver.findElement(By.cssSelector(" .el-table__body-wrapper .el-icon")).click();
    Thread.sleep(1000);
    //筛选查询job信息操作点击
    showOpertJobRunMessage(driver,applyName,jobName,combinName);
    //step运行消息的操作点击
    showOpertStepRunMessage(driver,applyName,jobName,combinName);
  }

  /*job运行历史点击方法*/
    public void jobRunHistory(WebDriver driver, String applyName, String jobName, String combinName) throws InterruptedException {
        //作业管理点击driver.findElement(By.cssSelector(".is-opened .el-menu-item:nth-child(3) > span")).click();
        //点击作业管理中的JOB运行历史
        Thread.sleep(1000);
        this.driver.findElement(By.xpath("//span[contains(.,'JOB运行历史')]")).click();
        Thread.sleep(1000);
        //筛选应用名称
        this.driver.findElement(By.xpath("//input[@type='text']")).click();
        Thread.sleep(1000);
        this.driver.findElement(By.xpath(applyName)).click();
        Thread.sleep(1000);
        //筛选Job名称
        this.driver.findElement(By.xpath("//div[2]/div/div/div/span/span/i")).click();
        Thread.sleep(1000);
        this.driver.findElement(
                By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/form/div[2]/div/div/div/input")).sendKeys(jobName);
        Thread.sleep(1000);
        this.driver.findElement(By.xpath(combinName)).click();
        Thread.sleep(1000);
        //搜索按钮点击
        this.driver.findElement(By.cssSelector(".el-form-item__content > .el-button")).click();
        Thread.sleep(1000);
        //同一个job，第一个job运行历史的 >符号
        driver.findElement(By.cssSelector(".el-table__body-wrapper .el-table__row:nth-child(1) .el-icon")).click();
        Thread.sleep(1000);
        //同一个job，第一个job运行历史的 >符号
        this.driver.findElement(By.xpath("/html/body/div/div/div[2]/div[2]/div/div/div/div[2]/div[4]/div[2]/table/tbody/tr/td[8]/div/div")).click();
        Thread.sleep(1000);
        //点击查看job运行信息
        this.driver.findElement(By.xpath("//body/ul/li[2]/button/span")).click();
        Thread.sleep(1000);
        //页签点击JOB历史信息
        driver.findElement(By.linkText("JOB历史信息")).click();
        Thread.sleep(1000);
        //查看job历史运行，点击操作
        this.driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[4]/div[2]/table/tbody/tr/td[8]/div/div")).click();
        {
            WebElement element = this.driver.findElement(By.cssSelector(".el-table__fixed-body-wrapper .el-dropdown > .el-button > span"));
            Actions builder = new Actions(this.driver);
            builder.moveToElement(element).perform();
            Thread.sleep(1000);
        }
        {
            WebElement element = this.driver.findElement(By.tagName("body"));
            Actions builder = new Actions(this.driver);
            builder.moveToElement(element, 0, 0).perform();
            Thread.sleep(1000);
        }
        //操作区域点击
        this.driver.findElement(By.xpath("//body/ul/li[1]/button/span")).click();
        //step运行消息的操作点击
        showOpertStepRunMessage(driver,applyName,jobName,combinName);
    }
}
