ftp:
  nodes: node1,node2,node3  #系统加载的文件服务器节点
  isBinaryMode: true #是否使用二进制传输 默认开启
  isActive: false #
  controlEncoding: GBK #管理通道字符集，默认GBK
  defaultLocalDir: /Users/yangguangyu/Documents/DCITS/DEMO/galaxy-test/src/main/resources/ftp #默认全局本地工作路径
  node1: #节点ID，必须在nodes定义的列表中，否则不会加载
    isDefault : true  #是否是默认节点，只能配置一个节点为默认节点，否则会出现混乱
    protocol: sftp #该节点使用的文件传输协议
    host: 10.7.19.115 #文件服务器IP
    port: 22 #文件服务器端口
    userName: sonic #用户名
    password: sonic #密码
    remoteDir: /home/sonic/galaxy-ftp-1/ #文件服务器工作路径，可以不指定，默认使用用户目录
    localDir:  /Users/yangguangyu/Documents/DCITS/DEMO/galaxy-test/src/main/resources/ftp #本地工作路径，在配置的情况下会覆盖defaultLocalDir
  node2:
    protocol: sftp
    host: 10.7.19.115
    port: 22
    userName: sonic
    password: sonic
    remoteDir: /home/sonic/galaxy-ftp-2/
  node3:
    protocol: ftp
    host: 127.0.0.1
    port: 21
    userName: Rae
    password: 1